quarkus.datasource.db-kind=mariadb
quarkus.datasource.devservices.enabled=false
MARIADB_USER=root
MARIADB_PASSWORD=root
quarkus.datasource.username=${MARIADB_USER}
quarkus.datasource.password=${MARIADB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:mariadb://${MARIADB_HOST:localhost}:${MARIADB_PORT:3306}/vocabulary
quarkus.http.root-path=/vocabulary

%dev.vocabulary.seed.enabled=true
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/http:\\/\\/localhost(:[0-9]+)?/,/http:\\/\\/127\\.0\\.0\\.1(:[0-9]+)?/

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.vocabulary.seed.enabled=false

%prod.quarkus.hibernate-orm.schema-management.strategy=none
