quarkus.datasource.db-kind=mariadb
quarkus.datasource.devservices.db-name=vocabulary
quarkus.http.root-path=/vocabulary

%dev.vocabulary.seed.enabled=true
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/./

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.vocabulary.seed.enabled=false
%test.quarkus.devservices.enabled=false
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:vocabulary;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE

%prod.quarkus.datasource.username=${MARIADB_USER:vocabulary}
%prod.quarkus.datasource.password=${MARIADB_PASSWORD:vocabulary}
%prod.quarkus.datasource.jdbc.url=jdbc:mariadb://${MARIADB_HOST:localhost}:3306/vocabulary
%prod.quarkus.hibernate-orm.schema-management.strategy=none
