quarkus.datasource.db-kind=mariadb
quarkus.datasource.devservices.db-name=vocabulary
quarkus.http.root-path=/vocabulary

%dev.vocabulary.seed.enabled=true
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/./

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%prod.quarkus.datasource.username=${MARIADB_USER:vocabulary}
%prod.quarkus.datasource.password=${MARIADB_PASSWORD:vocabulary}
%prod.quarkus.datasource.jdbc.url=jdbc:mariadb://${MARIADB_HOST:localhost}:3306/vocabulary
%prod.quarkus.hibernate-orm.schema-management.strategy=none
